### ISSUE TITLE
optional table parameter if sql query is specified

### ISSUE THREAD

**Issue by hlake21** [spotify/dbeam#127]
I was wondering why table is mandatory parameter if query based import is supported. should this get fixed?

**Comment by labianchin** [comment]
Good question!

I think table parameter is used when generating the Avro schema. If not, feel free to send a PR that a) remove the mandatory requirement b) tests/exercises the behavior in case `--table` table is missing and `--sqlFile`  is present.

**Comment by HectorLagos** [comment]
even if table is used to generate avro schema, I think it should be done using the query instead, will take a look and confirm
