### ISSUE TITLE
Add support for executing pre commands

### ISSUE THREAD

**Issue by labianchin** [spotify/dbeam#16]
Add a command line argument, like `--preCommand="SET worker_mem='4GB';" --preCommand="SET random_page_cost=1.1;",` where the session can be configured before executing the extraction query.

We can name the argument/option as `--preCommand`, `--preExecute` or something else..

**Comment by HectorLagos** [comment]
still need help on this ?

**Comment by labianchin** [comment]
We can close this, it was solved by #128 .
