### ISSUE TITLE
Provide more configuration for avro extraction

### ISSUE THREAD

**Issue by labianchin** [spotify/dbeam#18]
It would be good to expose more configuration to extract data for dbeam:

- [ ] `--fetchSize`: [`jdbcStatement` `fetchSize` configuration](https://github.com/spotify/dbeam/blob/master/dbeam/src/main/scala/com/spotify/dbeam/JdbcAvroIO.java#L200)
- [ ] `--avroCodec` / `--codecCompression`: configure [avro codec](https://github.com/spotify/dbeam/blob/master/dbeam/src/main/scala/com/spotify/dbeam/JdbcAvroIO.java#L66)

**Comment by hienle-hps** [comment]
@labianchin The "ResultSet" section of the [MySQL JDBC documentation](https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-implementation-notes.html) suggests even the [existing `setFetchSize`](https://github.com/spotify/dbeam/blob/master/dbeam-core/src/main/scala/com/spotify/dbeam/JdbcAvroIO.java#L200) is ignored unless `?useCursorFetch=true` was specified on the connection string.

Can dbeam be used to dump an entire MySQL database? I'm interested in dumping 20M+ tables (`mysqldump --tab` output isn't 100% compatible with BigQuery CSV parser), and am interested in how to modify the `SELECT * from <table>` to partition by the auto-increment primary key and run in parallel.

**Comment by labianchin** [comment]
> I'm interested in dumping 20M+ tables 

I don't think that would be a problem. We've been exporting 60M+ PSQL view with joins and 400M+ tables (with no joins).

> am interested in how to modify the SELECT * from <table> to partition by the auto-increment primary key and run in parallel

There isn't automatic support for that yet. Sqoop does support that by running `select max(id), min(id)` and partitioning by that. If you still want to run exports in parallel I suggest you create N views `SELECT * FROM table WHERE id BETWEEN 1 AND 10000000` and N dbeam exports (one for each view.

**Comment by hienle-hps** [comment]
I ended up using the [streaming value](https://github.com/spotify/dbeam/compare/master...hienle-hps:dataflow_streaming) `Integer.MIN_VALUE` to avoid the OOM, and kept the CloudSQL and small Dataflow instances in the same region/zone to minimize latency.
