### ISSUE TITLE
readme needs improvement

### ISSUE THREAD

**Issue by hilliao** [spotify/dbeam#21]
1. The [Scio](https://github.com/spotify/dbeam/blob/master/scio) broke in the Readme content 
2. The Examples can't run easily. The following command after I changed CLASS_PATH dbeam-core_2.12.jar to dbeam/target/scala-2.12/*.jar, I got error Error: Unable to initialize main class com.spotify.dbeam.JdbcAvroJob
Caused by: java.lang.NoClassDefFoundError: org/slf4j/Logger
```
java -cp CLASS_PATH dbeam-core_2.12.jar com.spotify.dbeam.JdbcAvroJob \
  --output=gs://my-testing-bucket-name/ \
  --username=my_database_username \
  --password=secret \
  --connectionUrl=jdbc:postgresql://some.database.uri.example.org:5432/my_database \
  --table=my_table
```
Can you provide more concrete examples? I am trying to figure out how to run from reading ./dbeam-pack/target/pack/bin/jdbc-avro-job. An example of how to run it in Google cloud dataflow with [mvn compile exec:java](https://cloud.google.com/dataflow/docs/quickstarts/quickstart-java-maven) would be nice. 

3. Instead of running ./dbeam-pack/target/pack/bin/jdbc-avro-job, how about a full example?
```
bash -v ./dbeam-pack/target/pack/bin/jdbc-avro-job --connectionUrl=jdbc:postgresql://some.database.uri.example.org:5432/my_database --table=my_table --output=gs://my-testing-bucket-name/  --username=my_database_username --password=secret
```

**Comment by labianchin** [comment]
DBeam no longer uses Scio and now has simpler and pinned dependencies. Since the, the README.md has been iterated and improved.

Closing the issue as outdated. If there are more things to act, we can follow up with new issues.
