### ISSUE TITLE
Handling of unsigned int fields in MySQL

### ISSUE THREAD

**Issue by robwil** [spotify/dbeam#294]
I think the [computeMapping function](https://github.com/spotify/dbeam/blob/master/dbeam-core/src/main/java/com/spotify/dbeam/avro/JdbcAvroRecord.java#L76) does not properly handle unsigned int fields in MySQL. It winds up calling `.getInt(..)` on a value that may be greater than the int max due to having unsigned only values in it.

https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-type-conversions.html seems to suggest that GetColumnClassName rather than GetColumnTypeName will return the correct type (long instead of int) for these cases, but I have not been able to confirm that.

Example error:

```
java.sql.SQLDataException: Value '2190526558' is outside of valid range for type java.lang.Integer 
com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:114) 
com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) 
com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) 
com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) 
com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) 
com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:92) 
com.mysql.cj.jdbc.result.ResultSetImpl.getObject(ResultSetImpl.java:1382) 
com.mysql.cj.jdbc.result.ResultSetImpl.getInt(ResultSetImpl.java:786) 
com.spotify.dbeam.avro.JdbcAvroRecord.lambda$computeMapping$3(JdbcAvroRecord.java:96)

```

**Comment by robwil** [comment]
Just noting a workaround if anyone else has this problem, you can define a VIEW that does a `CAST(`field` AS UNSIGNED INTEGER) as field` which will cause MySQL to return it as a BIGINT, which will be properly treated as a Long by DBeam.

**Comment by rulle-io** [comment]
@robwil What is a native MySQL column type in your case?

**Comment by robwil** [comment]
@rulle-io yes, exactly. The MySQL column type is `int unsigned`. In the CREATE TABLE, it shows as `int(10) unsigned` to be exact.

**Comment by bl4ze2509** [comment]
Hi @robwil I was also facing this issue for a field called userId in my spring project entity when I called the MAX(user_id) query through a get method in one the DAO implementation classes. I came up with the solution where I used @Column(name="user_id", columnDefinition="INT UNISIGNED(10)") annotation on the userId field in the entity code. I am not sure if that would work. Do you know if this would solve the issue?
@rulle-io can you also help me for this issue 🙏. I will really grateful for your help guys!

**Comment by rulle-io** [comment]
Hi @bl4ze2509,
dbeam constructs the AVRO schema based on JDBC Connection metadata, so it depends on the database and JDBC driver implementation.
The best way forward is to try and run your data extraction and see what happens.
It should work.

**Comment by bl4ze2509** [comment]
Yes I would definitely try this solution. Thank you so .uch @rulle-io 🤝😁
