### ISSUE TITLE
Support for query

### ISSUE THREAD

**Issue by satishrao84** [spotify/dbeam#394]
Hello,

Does dbeam support passing in queries as an option? I can pass in a table name, but what if i want to get the avro output of a query (table maybe joined with other tables or only select attributes)? 
if you don't support it, any plans to support it in future?

**Comment by rulle-io** [comment]
Try to use `--sqlFile` parameter:
```
--sqlFile=<String>
    A path to a file containing a SQL query (used instead of --table parameter).
```

**Comment by satishrao84** [comment]
Thanks! should have read the documentation more clearly!
