### ISSUE TITLE
Any support to write Avro back into MySQL or PostGres?

### ISSUE THREAD

**Issue by satishrao84** [spotify/dbeam#395]
Hello,

Would any of you know how we can load the avro files into a table in MySQL or Postgres? I see it's not probably supported here, but any chance that you'd know of another repo that would support that?

Thanks

**Comment by labianchin** [comment]
Hi. No plans for now on adding such support on DBeam to import data from Avro into SQL databases.

As an alternative, have a look at `JdbcIO.write()` either from [Beam SDK](https://beam.apache.org/releases/javadoc/2.35.0/org/apache/beam/sdk/io/jdbc/JdbcIO.html) or [Scio](https://github.com/spotify/scio/blob/main/scio-jdbc/src/test/scala/com/spotify/scio/jdbc/JdbcTest.scala).
