### ISSUE TITLE
Support for parallel exports

### ISSUE THREAD

**Issue by labianchin** [spotify/dbeam#51]
Introduce support for running a single export as multiple SQL queries.

There might be multiple ways to support that:
1. User provides a way to split the exports. e.g. split `id` column on ranges `[0, 10000000]` , `[10000001, 20000000]`, ...
2. User specify parallelism, automatically detect splits. e.g. `SELECT min(id) as min_id, max(id) as max_id`.

**Comment by anish749** [comment]
I’ve started working on this one. Would share a wip PR soon !!

**Comment by anish749** [comment]
Closed via #52
